import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    /**
     * Placeholder images are SVGs generated by scripts/generate-images.mjs.
     * Next.js blocks SVG by default, so we allow them for this project.
     */
    dangerouslyAllowSVG: true,
    contentSecurityPolicy:
      "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
