/**
 * Shared types for SALAAR's HOME.
 */

export type ProductAvailability = "In Stock" | "Made to Order";

/** Marketing tags used for "Featured", "Best Selling" and "New" collections. */
export interface ProductTags {
  featured?: boolean;
  bestSelling?: boolean;
  isNew?: boolean;
}

/** A single product shown on cards, grids and the details page. */
export interface ProductItem {
  /** Unique id, e.g. "bedroom-sets-1" */
  id: string;
  /** URL slug used on /product/[slug] */
  slug: string;
  /** Category slug: bedroom-sets | wardrobes | side-tables | dressers-mirrors */
  category: string;
  /** Product display name (from info.json or auto-generated) */
  name: string;
  /** Optional price in VND – null means "price on request" */
  price: number | null;
  /** Public image path, e.g. "/products/bedroom-sets/1.jpg" */
  image: string;
  /** Optional per-product overrides (from info.json) */
  description?: string;
  material?: string;
  dimensions?: string;
  /** Finish / wood tone, e.g. "Walnut" – used for shop filtering */
  color?: string;
  /** Estimated delivery, e.g. "1–3 days" – used for shop filtering */
  deliveryTime?: string;
  availability?: ProductAvailability;
  tags?: ProductTags;
  /** Position within the collection – used for "Newest" sorting */
  order?: number;
}

/** Shape of public/images-manifest.json (generated by scripts/generate-images.mjs). */
export interface ImageManifest {
  logo: string | null;
  hero: string[];
  banners: string[];
  gallery: string[];
  products: Record<string, ProductItem[]>;
}

/** Static description of a furniture category. */
export interface CategoryInfo {
  slug: string;
  name: string;
  tagline: string;
  short: string;
  description: string;
  material: string;
  dimensions: string;
  /** Default delivery estimate used for products without one. */
  deliveryTime: string;
  /** Wood tones / finishes used for shop filtering and product enrichment. */
  colors: string[];
  seoTitle: string;
  seoDescription: string;
}

export interface FAQItem {
  question: string;
  answer: string;
}

export interface FAQGroup {
  title: string;
  items: FAQItem[];
}
