/**
 * SALAAR'S HOME – Theme Sync
 * ===========================
 * Reads src/data/theme.ts and regenerates styles/tokens.css so the
 * Tailwind v4 design tokens always match the editable theme file.
 *
 * Run automatically via `predev` / `prebuild`. Run manually with:
 *   node scripts/sync-theme.mjs
 */
import fs from "node:fs";
import path from "node:path";

const THEME_PATH = path.join(process.cwd(), "src", "data", "theme.ts");
const OUT_PATH = path.join(process.cwd(), "styles", "tokens.css");

const source = fs.readFileSync(THEME_PATH, "utf8");

/* Strip comments before parsing the object literal */
const noComments = source
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/(^|[^\w])[/][/].*$/gm, "$1");

const marker = "export const THEME =";
const markerIndex = noComments.indexOf(marker);
if (markerIndex === -1) {
  throw new Error("sync-theme: could not find `export const THEME =` in " + THEME_PATH);
}

/* Extract the balanced object literal */
const objStart = noComments.indexOf("{", markerIndex + marker.length);
if (objStart === -1) throw new Error("sync-theme: THEME has no object literal");

let depth = 0;
let inString = false;
let quote = "";
let end = -1;
for (let i = objStart; i < noComments.length; i++) {
  const ch = noComments[i];
  if (inString) {
    if (ch === "\\") i++;
    else if (ch === quote) inString = false;
  } else if (ch === '"' || ch === "'" || ch === "`") {
    inString = true;
    quote = ch;
  } else if (ch === "{") {
    depth++;
  } else if (ch === "}") {
    depth--;
    if (depth === 0) {
      end = i + 1;
      break;
    }
  }
}
if (end === -1) throw new Error("sync-theme: unbalanced braces in THEME literal");

const literal = noComments.slice(objStart, end);
const theme = new Function(`return (${literal});`)();

/* Semantic token → existing Tailwind class-name mapping */
const COLOR_ALIASES = {
  background: "cream",
  surface: "linen",
  section: "beige",
  text: "ink",
  primary: "ink-2",
  primaryDark: "ink-3",
  secondary: "wood",
  secondaryDeep: "wood-deep",
  secondaryLight: "wood-light",
  accent: "gold",
  accentSoft: "gold-soft",
  accentDeep: "gold-deep",
  accentPale: "gold-pale",
  muted: "stone",
  mutedLight: "mist",
  border: "line",
  success: "good",
};

const lines = [];
lines.push("/*");
lines.push(" * AUTO-GENERATED from src/data/theme.ts by scripts/sync-theme.mjs.");
lines.push(" * Do not edit this file directly – edit src/data/theme.ts instead.");
lines.push(" */");
lines.push("");
lines.push("@theme {");

for (const [key, value] of Object.entries(theme.colors ?? {})) {
  lines.push(`  --color-${key}: ${value};`);
}

/* New semantic classes (bg-primary, text-primary, ring-primary, …) */
lines.push(`  --color-primary: ${theme.colors.primary};`);
lines.push(`  --color-primary-dark: ${theme.colors.primaryDark};`);

/* Aliases so existing utility classes keep working */
for (const [semantic, alias] of Object.entries(COLOR_ALIASES)) {
  lines.push(`  --color-${alias}: var(--color-${semantic});`);
}

/* Fonts */
lines.push(`  --font-display: ${theme.fonts.headings};`);
lines.push(`  --font-sans: ${theme.fonts.body};`);

/* Shadows – keys are kebab-cased so `--shadow-card-hover` → `shadow-card-hover` */
for (const [key, value] of Object.entries(theme.shadows ?? {})) {
  const kebab = key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
  lines.push(`  --shadow-${kebab}: ${value};`);
}

lines.push("}");
lines.push("");

fs.writeFileSync(OUT_PATH, lines.join("\n"), "utf8");

console.log("\n  Theme synced → styles/tokens.css");
console.log(`  colors : ${Object.keys(theme.colors ?? {}).length} tokens`);
console.log(`  fonts  : ${theme.fonts.headingsName} · ${theme.fonts.bodyName}`);
console.log(`  shadows: ${Object.keys(theme.shadows ?? {}).length} tokens\n`);
